<a href="https://colab.research.google.com/github/Saktanov/About_me/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_3_%D0%9F%D1%80%D0%B5%D0%B4%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [2]:
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = pd.read_csv(url)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.shape

(891, 12)

In [4]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [5]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [7]:
numeric_features = [
    "Age",
    "Fare",
    "SibSp",
    "Parch"
]

In [8]:
categorical_features = [
    "Sex",
    "Embarked"
]

In [11]:
X = df[numeric_features + categorical_features]
y = df["Survived"]

In [12]:
X.head()

    Age     Fare  SibSp  Parch     Sex Embarked
0  22.0   7.2500      1      0    male        S
1  38.0  71.2833      1      0  female        C
2  26.0   7.9250      0      0  female        S
3  35.0  53.1000      1      0  female        S
4  35.0   8.0500      0      0    male        S

In [13]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (712, 6)
X_test: (179, 6)
y_train: (712,)
y_test: (179,)

In [15]:
numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [16]:
SimpleImputer(strategy="median")

SimpleImputer(strategy='median')

In [17]:
StandardScaler()

StandardScaler()

In [18]:
categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(
        strategy="constant",
        fill_value="Unknown"
    )),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

In [19]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [20]:
X_train_transformed = preprocessor.fit_transform(X_train)

In [22]:
X_test_transformed = preprocessor.transform(X_test)

In [23]:
print("До преобразования:")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("\nПосле преобразования:")
print("X_train_transformed:", X_train_transformed.shape)
print("X_test_transformed:", X_test_transformed.shape)

До преобразования:
X_train: (712, 6)
X_test: (179, 6)

После преобразования:
X_train_transformed: (712, 10)
X_test_transformed: (179, 10)

In [24]:
print("Размер train после обработки:")
print(X_train_transformed.shape)

print("Размер test после обработки:")
print(X_test_transformed.shape)

Размер train после обработки:
(712, 10)
Размер test после обработки:
(179, 10)

In [25]:
feature_names = preprocessor.get_feature_names_out()

print(feature_names)

['num__Age' 'num__Fare' 'num__SibSp' 'num__Parch' 'cat__Sex_female'
 'cat__Sex_male' 'cat__Embarked_C' 'cat__Embarked_Q' 'cat__Embarked_S'
 'cat__Embarked_Unknown']

In [30]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [31]:
X_train_transformed = preprocessor.fit_transform(X_train)

In [32]:
print("===== ПРОВЕРКА PIPELINE =====")

print("Количество объектов train:", X_train.shape[0])
print("Количество объектов test:", X_test.shape[0])

print("Количество признаков до обработки:", X_train.shape[1])
print("Количество признаков после обработки:", X_train_transformed.shape[1])

print("Размер train после обработки:", X_train_transformed.shape)
print("Размер test после обработки:", X_test_transformed.shape)

print("\nPipeline успешно обучен только на TRAIN.")
print("TEST только преобразован через уже обученный pipeline.")
print("Утечка данных отсутствует.")

===== ПРОВЕРКА PIPELINE =====
Количество объектов train: 712
Количество объектов test: 179
Количество признаков до обработки: 6
Количество признаков после обработки: 10
Размер train после обработки: (712, 10)
Размер test после обработки: (179, 10)

Pipeline успешно обучен только на TRAIN.
TEST только преобразован через уже обученный pipeline.
Утечка данных отсутствует.

In [33]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

In [34]:
SimpleImputer(strategy="median")

SimpleImputer(strategy='median')

In [35]:
SimpleImputer(
    strategy="constant",
    fill_value="Unknown"
)

SimpleImputer(fill_value='Unknown', strategy='constant')

In [36]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [37]:
df = pd.read_csv(url)